import { Typography } from "@mui/joy";
import { LinearGradient } from "react-text-gradients";

export default function Intro() {
  return (
    <Typography sx={{ color: "gray" }} level="body-md" textAlign={"center"}>
      TokenTip is a decentralized tipping platform for creators that allows you
      to tip other creators with their tokens. It has been built during the{" "}
      <br />
      🇬🇧 ETH Global London Hackathon 2024. <br />
      <br />
      You can sign in with{" "}
      <LinearGradient gradient={["to left", "#b92b27 ,#1565C0"]}>
        <Typography fontSize={18}>World ID</Typography>{" "}
      </LinearGradient>
      or a passkey. Your smart contract based,{" "}
      <LinearGradient gradient={["to left", "#b92b27 ,#1565C0"]}>
        <Typography fontSize={18}>4337 Account Abstraction wallet</Typography>
      </LinearGradient>{" "}
      is generated by the{" "}
      <LinearGradient gradient={["to left", "#b92b27 ,#1565C0"]}>
        <Typography fontSize={18}>Etherspot Prime SDK</Typography>
      </LinearGradient>
      . We're using{" "}
      <LinearGradient gradient={["to left", "#b92b27 ,#1565C0"]}>
        <Typography fontSize={18}>Arka Paymaster</Typography>
      </LinearGradient>{" "}
      to sponsor all transactions so users don't have to worry about gas. We've
      used{" "}
      <LinearGradient gradient={["to left", "#b92b27 ,#1565C0"]}>
        <Typography fontSize={18}>Stylus</Typography>
      </LinearGradient>{" "}
      to write a Smart Contract that stores
      <LinearGradient gradient={["to left", "#b92b27 ,#1565C0"]}>
        <Typography fontSize={18}>
          TokenTip Username &lt;-&gt; Wallet{" "}
        </Typography>
      </LinearGradient>
      mappings. The whole thing is deployed on{" "}
      <LinearGradient gradient={["to left", "#b92b27 ,#1565C0"]}>
        <Typography fontSize={18}>Base</Typography>
      </LinearGradient>
      .
    </Typography>
  );
}
